//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pankyfood.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_Alimento", ReplyAction="*")]
        Pankyfood.ServiceReference1.Insertar_AlimentoResponse Insertar_Alimento(Pankyfood.ServiceReference1.Insertar_AlimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_Alimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Insertar_AlimentoResponse> Insertar_AlimentoAsync(Pankyfood.ServiceReference1.Insertar_AlimentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Listado_AlimentoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado_Alimento", ReplyAction="*")]
        Pankyfood.ServiceReference1.Listado_AlimentoResponse Listado_Alimento(Pankyfood.ServiceReference1.Listado_AlimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado_Alimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Listado_AlimentoResponse> Listado_AlimentoAsync(Pankyfood.ServiceReference1.Listado_AlimentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Eliminar_AlimentoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Alimento", ReplyAction="*")]
        Pankyfood.ServiceReference1.Eliminar_AlimentoResponse Eliminar_Alimento(Pankyfood.ServiceReference1.Eliminar_AlimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Alimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Eliminar_AlimentoResponse> Eliminar_AlimentoAsync(Pankyfood.ServiceReference1.Eliminar_AlimentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Alimento", ReplyAction="*")]
        Pankyfood.ServiceReference1.Actualizar_AlimentoResponse Actualizar_Alimento(Pankyfood.ServiceReference1.Actualizar_AlimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Alimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Actualizar_AlimentoResponse> Actualizar_AlimentoAsync(Pankyfood.ServiceReference1.Actualizar_AlimentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insertar_AlimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar_Alimento", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Insertar_AlimentoRequestBody Body;
        
        public Insertar_AlimentoRequest() {
        }
        
        public Insertar_AlimentoRequest(Pankyfood.ServiceReference1.Insertar_AlimentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insertar_AlimentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float Precio;
        
        public Insertar_AlimentoRequestBody() {
        }
        
        public Insertar_AlimentoRequestBody(string Nombre, string Descripcion, float Precio) {
            this.Nombre = Nombre;
            this.Descripcion = Descripcion;
            this.Precio = Precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insertar_AlimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar_AlimentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Insertar_AlimentoResponseBody Body;
        
        public Insertar_AlimentoResponse() {
        }
        
        public Insertar_AlimentoResponse(Pankyfood.ServiceReference1.Insertar_AlimentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insertar_AlimentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insertar_AlimentoResult;
        
        public Insertar_AlimentoResponseBody() {
        }
        
        public Insertar_AlimentoResponseBody(string Insertar_AlimentoResult) {
            this.Insertar_AlimentoResult = Insertar_AlimentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listado_AlimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listado_Alimento", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Listado_AlimentoRequestBody Body;
        
        public Listado_AlimentoRequest() {
        }
        
        public Listado_AlimentoRequest(Pankyfood.ServiceReference1.Listado_AlimentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Listado_AlimentoRequestBody {
        
        public Listado_AlimentoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listado_AlimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listado_AlimentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Listado_AlimentoResponseBody Body;
        
        public Listado_AlimentoResponse() {
        }
        
        public Listado_AlimentoResponse(Pankyfood.ServiceReference1.Listado_AlimentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Listado_AlimentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Listado_AlimentoResult;
        
        public Listado_AlimentoResponseBody() {
        }
        
        public Listado_AlimentoResponseBody(string Listado_AlimentoResult) {
            this.Listado_AlimentoResult = Listado_AlimentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_AlimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_Alimento", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Eliminar_AlimentoRequestBody Body;
        
        public Eliminar_AlimentoRequest() {
        }
        
        public Eliminar_AlimentoRequest(Pankyfood.ServiceReference1.Eliminar_AlimentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_AlimentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public Eliminar_AlimentoRequestBody() {
        }
        
        public Eliminar_AlimentoRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_AlimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_AlimentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Eliminar_AlimentoResponseBody Body;
        
        public Eliminar_AlimentoResponse() {
        }
        
        public Eliminar_AlimentoResponse(Pankyfood.ServiceReference1.Eliminar_AlimentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_AlimentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Eliminar_AlimentoResult;
        
        public Eliminar_AlimentoResponseBody() {
        }
        
        public Eliminar_AlimentoResponseBody(string Eliminar_AlimentoResult) {
            this.Eliminar_AlimentoResult = Eliminar_AlimentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_AlimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_Alimento", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Actualizar_AlimentoRequestBody Body;
        
        public Actualizar_AlimentoRequest() {
        }
        
        public Actualizar_AlimentoRequest(Pankyfood.ServiceReference1.Actualizar_AlimentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualizar_AlimentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float Precio;
        
        public Actualizar_AlimentoRequestBody() {
        }
        
        public Actualizar_AlimentoRequestBody(int Id, string Nombre, string Descripcion, float Precio) {
            this.Id = Id;
            this.Nombre = Nombre;
            this.Descripcion = Descripcion;
            this.Precio = Precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_AlimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_AlimentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pankyfood.ServiceReference1.Actualizar_AlimentoResponseBody Body;
        
        public Actualizar_AlimentoResponse() {
        }
        
        public Actualizar_AlimentoResponse(Pankyfood.ServiceReference1.Actualizar_AlimentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualizar_AlimentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Actualizar_AlimentoResult;
        
        public Actualizar_AlimentoResponseBody() {
        }
        
        public Actualizar_AlimentoResponseBody(string Actualizar_AlimentoResult) {
            this.Actualizar_AlimentoResult = Actualizar_AlimentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Pankyfood.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Pankyfood.ServiceReference1.WebService1Soap>, Pankyfood.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pankyfood.ServiceReference1.Insertar_AlimentoResponse Pankyfood.ServiceReference1.WebService1Soap.Insertar_Alimento(Pankyfood.ServiceReference1.Insertar_AlimentoRequest request) {
            return base.Channel.Insertar_Alimento(request);
        }
        
        public string Insertar_Alimento(string Nombre, string Descripcion, float Precio) {
            Pankyfood.ServiceReference1.Insertar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Insertar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Insertar_AlimentoRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Precio = Precio;
            Pankyfood.ServiceReference1.Insertar_AlimentoResponse retVal = ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Insertar_Alimento(inValue);
            return retVal.Body.Insertar_AlimentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Insertar_AlimentoResponse> Pankyfood.ServiceReference1.WebService1Soap.Insertar_AlimentoAsync(Pankyfood.ServiceReference1.Insertar_AlimentoRequest request) {
            return base.Channel.Insertar_AlimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Insertar_AlimentoResponse> Insertar_AlimentoAsync(string Nombre, string Descripcion, float Precio) {
            Pankyfood.ServiceReference1.Insertar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Insertar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Insertar_AlimentoRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Precio = Precio;
            return ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Insertar_AlimentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pankyfood.ServiceReference1.Listado_AlimentoResponse Pankyfood.ServiceReference1.WebService1Soap.Listado_Alimento(Pankyfood.ServiceReference1.Listado_AlimentoRequest request) {
            return base.Channel.Listado_Alimento(request);
        }
        
        public string Listado_Alimento() {
            Pankyfood.ServiceReference1.Listado_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Listado_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Listado_AlimentoRequestBody();
            Pankyfood.ServiceReference1.Listado_AlimentoResponse retVal = ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Listado_Alimento(inValue);
            return retVal.Body.Listado_AlimentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Listado_AlimentoResponse> Pankyfood.ServiceReference1.WebService1Soap.Listado_AlimentoAsync(Pankyfood.ServiceReference1.Listado_AlimentoRequest request) {
            return base.Channel.Listado_AlimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Listado_AlimentoResponse> Listado_AlimentoAsync() {
            Pankyfood.ServiceReference1.Listado_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Listado_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Listado_AlimentoRequestBody();
            return ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Listado_AlimentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pankyfood.ServiceReference1.Eliminar_AlimentoResponse Pankyfood.ServiceReference1.WebService1Soap.Eliminar_Alimento(Pankyfood.ServiceReference1.Eliminar_AlimentoRequest request) {
            return base.Channel.Eliminar_Alimento(request);
        }
        
        public string Eliminar_Alimento(int Id) {
            Pankyfood.ServiceReference1.Eliminar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Eliminar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Eliminar_AlimentoRequestBody();
            inValue.Body.Id = Id;
            Pankyfood.ServiceReference1.Eliminar_AlimentoResponse retVal = ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Eliminar_Alimento(inValue);
            return retVal.Body.Eliminar_AlimentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Eliminar_AlimentoResponse> Pankyfood.ServiceReference1.WebService1Soap.Eliminar_AlimentoAsync(Pankyfood.ServiceReference1.Eliminar_AlimentoRequest request) {
            return base.Channel.Eliminar_AlimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Eliminar_AlimentoResponse> Eliminar_AlimentoAsync(int Id) {
            Pankyfood.ServiceReference1.Eliminar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Eliminar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Eliminar_AlimentoRequestBody();
            inValue.Body.Id = Id;
            return ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Eliminar_AlimentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pankyfood.ServiceReference1.Actualizar_AlimentoResponse Pankyfood.ServiceReference1.WebService1Soap.Actualizar_Alimento(Pankyfood.ServiceReference1.Actualizar_AlimentoRequest request) {
            return base.Channel.Actualizar_Alimento(request);
        }
        
        public string Actualizar_Alimento(int Id, string Nombre, string Descripcion, float Precio) {
            Pankyfood.ServiceReference1.Actualizar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Actualizar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Actualizar_AlimentoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Precio = Precio;
            Pankyfood.ServiceReference1.Actualizar_AlimentoResponse retVal = ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Actualizar_Alimento(inValue);
            return retVal.Body.Actualizar_AlimentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Actualizar_AlimentoResponse> Pankyfood.ServiceReference1.WebService1Soap.Actualizar_AlimentoAsync(Pankyfood.ServiceReference1.Actualizar_AlimentoRequest request) {
            return base.Channel.Actualizar_AlimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pankyfood.ServiceReference1.Actualizar_AlimentoResponse> Actualizar_AlimentoAsync(int Id, string Nombre, string Descripcion, float Precio) {
            Pankyfood.ServiceReference1.Actualizar_AlimentoRequest inValue = new Pankyfood.ServiceReference1.Actualizar_AlimentoRequest();
            inValue.Body = new Pankyfood.ServiceReference1.Actualizar_AlimentoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Precio = Precio;
            return ((Pankyfood.ServiceReference1.WebService1Soap)(this)).Actualizar_AlimentoAsync(inValue);
        }
    }
}
